const SMS_ROOT=window.SMS_ROOT||'';
const ROUTES={home:'',about:'about/',products:'products/',services:'services/',projects:'projects/',downloads:'downloads/',contact:'contact/'};
const PRODUCT_ROUTES={"automatic": "products/automatic-smoke-curtain/", "fixed": "products/fixed-smoke-curtain/", "ventilator": "products/smoke-ventilator-roof-wall/", "actuator": "products/actuator/", "glass": "products/glass-baffles/", "steel": "products/customized-steel-structure-design/"};
const SERVICE_ROUTES={"maintenance": "services/smoke-curtain-maintenance/", "pe": "services/professional-engineer-calculation/"};
const PROJECT_ROUTES={"avenue": "projects/avenue-k-mall/", "gateway": "projects/kl-gateway-mall/", "melawati": "projects/melawati-mall/", "damen": "projects/damen-usj-mall/", "aeon": "projects/aeon-mall-kulai-jaya/"};
const productData={"automatic": {"title": "Automatic Smoke Curtain", "short": "Automatic smoke curtain systems designed for controlled deployment as part of a building smoke management strategy.", "image": "assets/images/product-automatic-7bb4bd7f0159.png", "points": ["Automatic deployment", "Commercial applications", "Industrial applications", "Supply & installation"], "details": "Smoke Master Solution provides automatic smoke curtain solutions with project-specific supply, installation, maintenance and rectification support."}, "fixed": {"title": "Fixed Type Smoke Curtain", "short": "Fixed smoke curtain systems for permanent smoke containment in suitable commercial and industrial applications.", "image": "assets/images/product-fixed-2aba780acb86.png", "points": ["Fixed smoke barrier", "Industrial applications", "Commercial applications", "Project-specific installation"], "details": "Fixed type smoke curtains provide a permanent smoke barrier arrangement and can be coordinated around structural and project requirements."}, "ventilator": {"title": "Smoke Ventilator — Roof / Wall", "short": "Customized roof and wall smoke ventilators engineered to support natural smoke exhaust and ventilation requirements.", "image": "assets/images/product-ventilator-fdd65762f414.jpg", "points": ["Roof application", "Wall application", "Customized dimensions", "Engineering support"], "details": "Smoke Master Solution supplies customized smoke ventilator systems for roof, wall and combined applications."}, "actuator": {"title": "Actuator", "short": "Electric actuator solutions used to operate compatible smoke ventilation and smoke-control components.", "image": "https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1400&q=95", "points": ["Electric operation", "Smoke ventilation use", "System integration", "Project selection support"], "details": "Actuator selection is coordinated around the relevant opening, load and control requirements for the project."}, "glass": {"title": "Glass Baffles", "short": "Transparent glass baffle solutions for architectural smoke containment applications.", "image": "assets/images/product-glass-acb55a8e86d5.jpg", "points": ["Transparent smoke barrier", "Architectural integration", "Commercial applications", "Customized installation"], "details": "Glass baffles offer smoke containment while retaining a visually open architectural treatment."}, "steel": {"title": "Customized Steel Structure Design", "short": "Project-specific steel structure design and fabrication support for smoke control and ventilation installations.", "image": "assets/images/product-steel-adb0e1c0f964.jpg", "points": ["Customized support frame", "Engineering coordination", "Fabrication requirements", "Installation planning"], "details": "Smoke Master Solution supports customized steel structure requirements used to mount or integrate smoke-control and ventilation systems."}};
function go(path){
  const target=SMS_ROOT+path;
  // Local preview: browsers do not automatically resolve folder URLs to index.html on file://.
  // GitHub Pages / normal web hosting keeps the clean folder URL.
  if(location.protocol==='file:'){
    location.href=target+(target.endsWith('/')?'index.html':'');
  }else{
    location.href=target;
  }
}
function openPage(name){ go(ROUTES[name]??''); }
function showProductLobby(){go('products/')}
function showServiceLobby(){go('services/')}
function showProjectLobby(){go('projects/')}
function goDownloads(){go('downloads/')}
function openProductPage(key){if(PRODUCT_ROUTES[key])go(PRODUCT_ROUTES[key])}
function openServicePage(key){if(SERVICE_ROUTES[key])go(SERVICE_ROUTES[key])}
function openProjectPage(key){if(PROJECT_ROUTES[key])go(PROJECT_ROUTES[key])}
function openProject(key){openProjectPage(key)}
function closeMobile(){const n=document.getElementById('mobileNav');if(n)n.classList.remove('show')}
function toggleMobileGroup(id){const el=document.getElementById(id);document.querySelectorAll('.mobile-accordion').forEach(g=>{if(g!==el)g.classList.remove('open')});if(el)el.classList.toggle('open')}
function toggleProductCategories(btn){const panel=btn.closest('.product-category-panel');if(!panel)return;const open=panel.classList.toggle('open');btn.setAttribute('aria-expanded',open?'true':'false')}
function openDrawer(service){const d=document.getElementById('drawer'),o=document.getElementById('drawerOverlay');if(d)d.classList.add('show');if(o)o.classList.add('show');document.body.classList.add('locked');if(service){const sel=document.getElementById('drawerService');if(sel)[...sel.options].forEach(opt=>{if(opt.text.toLowerCase().includes(service.toLowerCase())||service.toLowerCase().includes(opt.text.toLowerCase()))sel.value=opt.value})}}
function closeDrawer(){const d=document.getElementById('drawer'),o=document.getElementById('drawerOverlay');if(d)d.classList.remove('show');if(o)o.classList.remove('show');document.body.classList.remove('locked')}
function closeModal(){const m=document.getElementById('modal');if(m)m.classList.remove('show');document.body.classList.remove('locked')}
let revealObserver;function observeReveals(){if(!('IntersectionObserver' in window)){document.querySelectorAll('.reveal-up').forEach(x=>x.classList.add('is-visible'));return};if(revealObserver)revealObserver.disconnect();revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('is-visible')}),{threshold:.12});document.querySelectorAll('.reveal-up').forEach(el=>revealObserver.observe(el))}
function buildHomeTabs(){const tabs=document.getElementById('productTabs');if(!tabs)return;tabs.innerHTML='';Object.entries(productData).forEach(([key,p],i)=>{const b=document.createElement('button');b.className='product-tab'+(i===0?' active':'');b.innerHTML='<span>'+p.title+'</span><span>→</span>';b.onclick=()=>selectHomeProduct(key,b);tabs.appendChild(b)});selectHomeProduct('automatic',tabs.children[0])}
function selectHomeProduct(key,btn){const p=productData[key];if(!p)return;document.querySelectorAll('.product-tab').forEach(x=>x.classList.remove('active'));if(btn)btn.classList.add('active');const t=document.getElementById('homeProductTitle'),tx=document.getElementById('homeProductText'),mn=document.getElementById('homeProductMini'),im=document.getElementById('homeProductImage'),bt=document.getElementById('homeProductBtn');if(t)t.textContent=p.title;if(tx)tx.textContent=p.short;if(mn)mn.innerHTML=p.points.map(x=>'<div>'+x+'</div>').join('');if(im)im.src=SMS_ROOT+p.image;if(bt)bt.onclick=()=>openProductPage(key)}
function startHeroRotation(){const hero=document.getElementById('heroRotator');if(!hero)return;const slides=[productData.automatic.image,productData.fixed.image,productData.ventilator.image].map(x=>SMS_ROOT+x);let i=0;hero.src=slides[0];setInterval(()=>{i=(i+1)%slides.length;hero.classList.remove('hero-fade');void hero.offsetWidth;hero.src=slides[i];hero.classList.add('hero-fade')},4200)}
function initHomeProductDropdown(){const tabs=document.querySelector('#page-home .product-tabs');if(!tabs||tabs.dataset.mobileAccordionReady==='1')return;tabs.dataset.mobileAccordionReady='1';tabs.addEventListener('click',e=>{if(innerWidth>700)return;const tab=e.target.closest('.product-tab');if(tab){setTimeout(()=>tabs.classList.remove('mobile-open'),30);return}const rect=tabs.getBoundingClientRect();if(e.clientY-rect.top<=58)tabs.classList.toggle('mobile-open')})}
function setupForms(){const cf=document.getElementById('contactForm');if(cf)cf.onsubmit=e=>{e.preventDefault();const v=id=>document.getElementById(id)?.value||'-';const text=`Hi Smoke Master Solution,\n\nI would like to enquire about your products / services.\n\nName: ${v('contactName')}\nCompany: ${v('contactCompany')}\nPhone: ${v('contactPhone')}\nProduct / Service: ${document.getElementById('contactService')?.value||'General Enquiry'}\n\nRequirement:\n${v('contactMessage')}\n\nThank you.`;window.open('https://wa.me/60122702200?text='+encodeURIComponent(text),'_blank')};const df=document.getElementById('drawerForm');if(df)df.onsubmit=e=>{e.preventDefault();const v=id=>document.getElementById(id)?.value||'-';const text=`Hi Smoke Master Solution,\n\nI would like to discuss a project.\n\nName: ${v('drawerName')}\nCompany: ${v('drawerCompany')}\nProduct / Service: ${document.getElementById('drawerService')?.value||'General Consultation'}\nProject Location: ${v('drawerLocation')}\nProject Stage: ${document.getElementById('drawerStage')?.value||'-'}\n\nRequirements:\n${v('drawerMessage')}\n\nThank you.`;window.open('https://wa.me/60122702200?text='+encodeURIComponent(text),'_blank')}}
document.addEventListener('DOMContentLoaded',()=>{const mm=document.getElementById('mobileMenu');if(mm)mm.onclick=()=>document.getElementById('mobileNav')?.classList.toggle('show');document.getElementById('drawerOverlay')?.addEventListener('click',closeDrawer);document.getElementById('modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();closeModal();closeMobile()}});const yr=document.getElementById('year');if(yr)yr.textContent=new Date().getFullYear();const og=document.getElementById('ogUrl');if(og)og.content=location.href.split('#')[0].split('?')[0];buildHomeTabs();startHeroRotation();observeReveals();initHomeProductDropdown();setupForms();document.querySelectorAll('[data-page-link]').forEach(b=>b.classList.toggle('active',b.dataset.pageLink===document.body.dataset.section));});
window.addEventListener('load',()=>setTimeout(()=>{document.getElementById('preloader')?.classList.add('hide');document.body.classList.remove('preloading','locked')},1150));
